application:
    update_branch: stable
    backup_time_in_minutes: 10
    max_backups: 10

firewall: 
    active: True
    allowed_ips:
        - 127.0.0.1

server:
    auto_reload: False
    debugger: False
    evalex: False
    port: 1024

userinterface_defaults:
    language: de
    theme: black

contact:
    admin_name: Test Test
    contact_ways:
        -   name: Email
            link: mayilto:test@test.test
            icon: mail.svg

        -   name: Telegram
            link: https://telegram.me/username
            icon: telegram.svg

        -   name: WhatsApp
            link: https://wa.me/491525557912/
            icon: whatsapp.svg
